title: Eric Moore
subtitle: Endless learning, progress together!
language: en
timezone: Asia/Shanghai

url: https://eric-gitta-moore.github.io/en
permalink: :title/

archive_generator:
  per_page: 25

theme: maupassant

public_dir: ../public/en
