title: James Curtis
subtitle: Endless learning, progress together!
language: en
timezone: Asia/Shanghai

url: https://james-curtis.github.io/en
permalink: :title/

archive_generator:
  per_page: 25

theme: maupassant

public_dir: ../public/en
