title: James Curtis
subtitle: 大事小事都记下来
language: zh-CN
timezone: Asia/Shanghai

url: https://james-curtis.github.io
permalink: :title/

# Generate an archive of posts, powered by hexo-generator-index	
index_generator:
  per_page: 50

theme: maupassant
