title: James Curtis
subtitle: 大事小事都记下来
language: zh-CN
timezone: Asia/Shanghai

url: https://james-curtis.github.io
permalink: :title/

# global pagination
per_page: 50

# home pagination
index_generator:
  per_page: 10

theme: maupassant
