utterances: ## See: https://utteranc.es
  enable: true ## If you want to use Utterances comment system, please set the value to true.
  repo: james-curtis/james-curtis.github.io ## The repository utterances will connect to, e.g. tufu9441/comments
  identifier: pathname ## The mapping between blog posts and GitHub issues.

google_search: false ## Use Google search, true/false.
self_search: true ## Use a jQuery-based local search engine, true/false.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: false ## If you want to add list number to toc please set the value to true.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
wordcount: true ## If you want to display the word counter and the reading time expected to spend of each post please set the value to true, and you must have hexo-wordcount installed.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

info:
  avatar: /img/avatar.png
  discription: To be a better man.
  outlinkitem:
    - name: twitter
      outlink: https://twitter.com/username
      message: Twitter
    - name: envelope
      outlink: mailto:admin@domain.com
      message: Email
    - name: github
      outlink: https://github.com/username
      message: Github
    - name: rss
      outlink: /atom.xml
      message: RSS

links:
  - title: Google
    url: //james-curtis.github.io
    src: //james-curtis.github.io
    desc: just life
  - title: Twitter
    url: //james-curtis.github.io
    src: //james-curtis.github.io
    desc: just life
  - title: Reddit
    url: //james-curtis.github.io
    src: //james-curtis.github.io
    desc: just life
